#!/usr/bin/env bash

(
  rm -r dist 2>/dev/null
  rm -r lib 2>/dev/null

  pnpm tsup src --format cjs,esm --no-splitting --dts

  mv dist lib

  cp README.md lib/README.md && \
  cp LICENSE lib/LICENSE && \
  node ./scripts/tinyit.js
)
